Ajout d'une documentation pour installer cote software le boutton pou…
mdl29/donkeycarLPH pull request #12
Opened 2022-03-12 13:47 UTC by Minemew2

…ssoir
Fix #3

2022-03-12 13:48 UTC, Benvii commented
Je vais voir pour le tester sur monkeycar et faire la review en même temps.

2022-03-12 17:33 UTC, Benvii requested changes
Doc super bien expliquée, j'ai juste rajouter quelques petite suggestion de modifs.

Testé et approuvé sur monkecar

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# apt-get install wiringpi
Ajoute un `sudo` stp

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# nano /root/pin-shutdown.sh
Ajoute un sudo aussi

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# vim /root/pin-shutdown.sh
vim n'est pas install sur la rpi tu peux enlever

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# chmod +x /root/pin-shutdown.sh
Ajouter un sudo

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +Premièrement, il faut créer le fichier de notre service. Pour cela, on réutilise un logiciel de traitement de texte. On va enrengistrer notre service dans le fichier /etc/systemd/system/
`On va enregistrer`

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# nano /etc/systemd/system/button-shutdown.service
sudo

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# systemctl daemon-reload
sudo

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# systemctl enable button-shutdown.service
sudo

2022-03-12 17:33 UTC, Benvii commented on Boutton_poussoir.md
> +# systemctl start button-shutdown.service
sudo

2022-03-14 11:49 UTC, Minemew2 commented
Pour les sudo Titouan ou Pier (je sais plus lequel) m'a dit que dans les conventions le # signifie forcément qu'on éxecute la commande en root, donc en sudo

2022-03-14 12:06 UTC, Benvii commented
> Pour les sudo Titouan ou Pier (je sais plus lequel) m'a dit que dans les conventions le # signifie forcément qu'on éxecute la commande en root, donc en sudo

En effet j'avais pas fait gaffe au `#`

2022-03-19 14:18 UTC, Minemew2 commented on Boutton_poussoir.md
> +# vim /root/pin-shutdown.sh
J'ai enlevé cette option

2022-03-19 14:18 UTC, Minemew2 commented on Boutton_poussoir.md
> +Premièrement, il faut créer le fichier de notre service. Pour cela, on réutilise un logiciel de traitement de texte. On va enrengistrer notre service dans le fichier /etc/systemd/system/
Corrigé

2022-04-12 18:54 UTC, yannis-mlgrn commented
on merge ?

2022-04-12 19:14 UTC, merged

2022-04-12 19:14 UTC, Benvii commented
Yes @yannis-mlgrn je merge