Resolves #176 : Creation of jobs bug
mdl29/donkeycarLPH pull request #177
Opened 2022-07-04 21:35 UTC by yannis-mlgrn

- Fixes #176 
## Features : 
- Fixed bug, now we can crate multiples jobs linked to the same player
-  improve submit button of register popup for phone clients

2022-07-08 22:19 UTC, yannis-mlgrn commented
LGTM

2022-09-15 20:19 UTC, Benvii requested changes
Small change required, conditional optimisation.

Algo : 

- Fetch player as this.player
- If not existing: create it;  set this.player
- Create the job (not in a conditional block)

2022-09-15 20:19 UTC, Benvii commented on donkeycarManagerFront/src/components/register.vue
>          await srv.addJobs(this.player.player_id)
This should be outside the condition, in both case you will create the job you have duplicate code.

2022-09-15 20:19 UTC, Benvii commented on donkeycarManagerFront/src/components/register.vue
> +        await srv.addJobs(this.playerTest[0].player_id)
Duplicated, put it outside the conditional block will be cleaner, less lines => less bugs

2022-09-17 13:27 UTC, viandoxdev commented
Closing for now since #180 should already fix that.

2022-09-17 13:27 UTC, closed without merging