Resolves #235 : Add jsfw documentation
mdl29/donkeycarLPH pull request #237
Opened 2023-01-21 14:07 UTC by yannis-mlgrn

Fixes #235 
## Features : 
- 📝 Add jsfw documentation

2023-01-21 20:46 UTC, viandoxdev requested changes

2023-01-21 20:46 UTC, viandoxdev commented on doc/jsfw/documentation.md
> +cd jsfw
add 
```bash
git checkout e371ef3ec4053d83abad683289f91a447d9e92ed
```
after cd

2023-01-22 20:42 UTC, yannis-mlgrn commented on doc/jsfw/documentation.md
> +cd jsfw
fixed here [eb91979](https://github.com/mdl29/donkeycarLPH/pull/237/commits/eb919791a6cdd13f907466166147df454249af17)

2023-01-22 22:31 UTC, viandoxdev approved these changes

2023-01-28 10:06 UTC, yannis-mlgrn commented
LGTM !

2023-02-04 15:09 UTC, viandoxdev commented
Closed in favor of #242

2023-02-04 15:09 UTC, closed without merging