Disable the daily upgrade service
mdl29/donkeycarLPH pull request #51
Opened 2022-04-23 14:26 UTC by viandoxdev

2022-06-11 17:59 UTC, viandoxdev commented
why tho

2022-07-08 14:38 UTC, viandoxdev commented
Reopening as it might be useful

2022-07-09 21:24 UTC, yannis-mlgrn commented on ansible/donkeycar.yml
> +      become: yes
Better in my-car

2022-07-09 21:24 UTC, yannis-mlgrn commented on ansible/roles/optimizations/tasks/main.yml
> +    state: disabled
missing i think some others services, see that : https://superuser.com/questions/1327884/how-to-disable-daily-upgrade-and-clean-on-ubuntu-16-04

2022-07-09 21:24 UTC, yannis-mlgrn commented
please fix conflicts @viandoxdev

2022-07-09 22:00 UTC, viandoxdev commented
done

2022-07-09 22:21 UTC, yannis-mlgrn commented
normally done

2022-07-13 12:41 UTC, yannis-mlgrn requested changes

2022-07-13 12:41 UTC, yannis-mlgrn commented on ansible/roles/optimizations/tasks/main.yml
> +    - 'apt-daily.service'
You need according to the answer of this [problem](https://superuser.com/questions/1327884/how-to-disable-daily-upgrade-and-clean-on-ubuntu-16-04), you need to remove `unattended-upgrades` , stopped `apt-daily.timer` service before disable these services.
The code might be like this : 
```yaml
---

- name: Remove unattended-upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent

- name: stopped daily upgrades
  systemd:
    name: "apt-daily.timer"
    state: stopped

- name: Disable daily upgrades
  systemd:
    name: "{{ item }}"
    state: disabled
    daemon-reload: yes
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily.service'
```

2022-07-13 16:32 UTC, yannis-mlgrn commented on ansible/roles/optimizations/tasks/main.yml
> +    state: disabled
You have made a mistake here, according to [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html), `state` parameter can't take `disable`. For disable a service you must replace it by `stopped`  and add this line : `enabled: false
### Final code should be : 
```yaml
---

- name: Disable daily upgrades
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon-reload: yes
  with_items:
    - 'apt-daily-upgrade.timer'
    - 'apt-daily.timer'
    - 'apt-daily.service'
 ```

2022-07-13 16:32 UTC, yannis-mlgrn requested changes

2022-07-13 16:32 UTC, yannis-mlgrn commented on ansible/roles/optimizations/tasks/main.yml
> +    state: disabled
You have made a mistake here, according to [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html), `state` parameter can't take `disable`. For disable a service you must replace it by `stopped`  and add this line : `enabled: false
### Final code should be : 
```yaml
---

- name: Disable daily upgrades
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon-reload: yes
  with_items:
    - 'apt-daily-upgrade.timer'
    - 'apt-daily.timer'
    - 'apt-daily.service'
 ```

2022-08-28 16:41 UTC, yannis-mlgrn approved these changes
LGTM

2022-09-15 19:19 UTC, Benvii approved these changes
Ok for me

2022-09-15 19:19 UTC, Benvii commented on ansible/donkeycar.yml
> +    - role: raspi-config #rasperry pi confiuguration role
Spelling mistake it was good before ^^

2022-09-15 19:20 UTC, merged